DROP TABLE T_TESTE_DDL_AUTO CASCADE CONSTRAINTS;

CREATE TABLE T_TESTE_DDL_AUTO(
    CD_TESTE NUMBER(3) GENERATED ALWAYS AS IDENTITY,
    NM_TESTE VARCHAR2(30)
);

INSERT INTO T_TESTE_DDL_AUTO (
    NM_TESTE
) VALUES(
    'TESTE AUTO'
);

SELECT
    *
FROM
    T_TESTE_DDL_AUTO;