DROP TABLE T_TESTE_DDL_SEQUENCE CASCADE CONSTRAINTS;

CREATE TABLE T_TESTE_DDL_SEQUENCE (
    CD_TESTE_SQ NUMBER(3) NOT NULL,
    NM_TESTE_SQ VARCHAR2(30) NOT NULL
);

ALTER TABLE T_TESTE_DDL_SEQUENCE
    ADD CONSTRAINT PK_TESTE_DDL_SEQUENCE PRIMARY KEY (
        CD_TESTE_SQ
    );

DROP SEQUENCE SQ_TESTE_DDL_SEQUENCE;

CREATE SEQUENCE SQ_TESTE_DDL_SEQUENCE
START WITH 100 --Primeiro número a ser gerado
INCREMENT BY 1 --Valor do incremento (!= zero)
MAXVALUE 999 --Valor máximo da sequencia
NOCACHE --NOCAHCE: sem cache
NOCYCLE;

--Após chegar ao limite, não reinicia

INSERT INTO T_TESTE_DDL_SEQUENCE VALUES (
    SQ_TESTE_DDL_SEQUENCE.NEXTVAL,
    'TESTE'
);

--RODAR DUAS VEZES

SELECT
    *
FROM
    T_TESTE_DDL_SEQUENCE;

SELECT
    SQ_TESTE_DDL_SEQUENCE.CURRVAL
FROM
    DUAL;

--CURRVAL: valor atual, ultimo valor da sequencia

SELECT
    *
FROM
    USER_SEQUENCES
WHERE
    SEQUENCE_NAME = 'SQ_TESTE_DDL_SEQUENCE';

--ALTERANDO A SEQUENCE
ALTER SEQUENCE SQ_TESTE_DDL_SEQUENCE START WITH 100 MAXVALUE 999;

SELECT
    *
FROM
    USER_SEQUENCES
WHERE
    SEQUENCE_NAME = 'SQ_TESTE_DDL_SEQUENCE';

INSERT INTO T_TESTE_DDL_SEQUENCE VALUES (
    SQ_TESTE_DDL_SEQUENCE.NEXTVAL,
    'TESTE'
);

--RODAR DUAS VEZES

SELECT
    *
FROM
    T_TESTE_DDL_SEQUENCE;

DROP SEQUENCE SQ_TESTE_DDL_SEQUENCE;

--------------------------------------------
--TRIGGER
--------------------------------------------
CREATE OR REPLACE TRIGGER TRG_TESTE_DDL_SEQUENCE BEFORE
    INSERT ON T_TESTE_DDL_SEQUENCE FOR EACH ROW
BEGIN
    :NEW.CD_TESTE_SQ := SQ_TESTE_DDL_SEQUENCE.NEXTVAL;
END;
/

SELECT
    SQ_TESTE_DDL_SEQUENCE.CURRVAL
FROM
    DUAL;

INSERT INTO T_TESTE_DDL_SEQUENCE (
    NM_TESTE_SQ
) VALUES (
    'TESTE TRIGGER'
)